[workspace]

members = [
    "modtext",
    "schema",
]

resolver="2"

[workspace.dependencies]
flatbuffers = "=24.3.25"
schema = { path = "schema" }

[workspace.build-dependencies]
flatbuffers-build = "0.2.0" # +flatc-24.3.25
